CREATE TABLE public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  parent_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT ON public.categories TO anon;
GRANT SELECT ON public.categories TO authenticated;
GRANT ALL ON public.categories TO service_role;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Categories are public" ON public.categories FOR SELECT TO anon, authenticated USING (true);

CREATE TABLE public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  description TEXT NOT NULL DEFAULT '',
  base_price NUMERIC(12,2) NOT NULL DEFAULT 0,
  compare_at_price NUMERIC(12,2),
  status TEXT NOT NULL DEFAULT 'ACTIVE',
  image_key TEXT NOT NULL DEFAULT 'headphones',
  rating NUMERIC(3,2) NOT NULL DEFAULT 4.8,
  reviews_count INT NOT NULL DEFAULT 0,
  badge TEXT,
  category_id BIGINT NOT NULL REFERENCES public.categories(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT ON public.products TO anon;
GRANT SELECT ON public.products TO authenticated;
GRANT ALL ON public.products TO service_role;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Products are public" ON public.products FOR SELECT TO anon, authenticated USING (true);

CREATE TABLE public.product_variants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  sku TEXT NOT NULL UNIQUE,
  color TEXT NOT NULL DEFAULT '',
  size TEXT NOT NULL DEFAULT '',
  price NUMERIC(12,2) NOT NULL DEFAULT 0,
  stock INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT ON public.product_variants TO anon;
GRANT SELECT ON public.product_variants TO authenticated;
GRANT ALL ON public.product_variants TO service_role;
ALTER TABLE public.product_variants ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Variants are public" ON public.product_variants FOR SELECT TO anon, authenticated USING (true);

CREATE TABLE public.cart_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  variant_id BIGINT NOT NULL REFERENCES public.product_variants(id) ON DELETE CASCADE,
  quantity INT NOT NULL DEFAULT 1 CHECK (quantity > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, variant_id)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.cart_items TO authenticated;
GRANT ALL ON public.cart_items TO service_role;
ALTER TABLE public.cart_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users manage own cart" ON public.cart_items FOR ALL TO authenticated
  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE TABLE public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  total_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  shipping_recipient_name TEXT NOT NULL,
  shipping_phone TEXT NOT NULL,
  shipping_address_line TEXT NOT NULL,
  shipping_city TEXT NOT NULL,
  payment_method TEXT NOT NULL DEFAULT 'cod',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE ON public.orders TO authenticated;
GRANT ALL ON public.orders TO service_role;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users read own orders" ON public.orders FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users create own orders" ON public.orders FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users cancel pending orders" ON public.orders FOR UPDATE TO authenticated
  USING (auth.uid() = user_id AND status = 'pending')
  WITH CHECK (auth.uid() = user_id AND status IN ('pending','cancelled'));

CREATE TABLE public.order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  variant_id BIGINT REFERENCES public.product_variants(id) ON DELETE SET NULL,
  product_name_snapshot TEXT NOT NULL,
  sku_snapshot TEXT NOT NULL DEFAULT '',
  size_snapshot TEXT NOT NULL DEFAULT '',
  color_snapshot TEXT NOT NULL DEFAULT '',
  image_key_snapshot TEXT NOT NULL DEFAULT 'headphones',
  unit_price_snapshot NUMERIC(12,2) NOT NULL DEFAULT 0,
  quantity INT NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT ON public.order_items TO authenticated;
GRANT ALL ON public.order_items TO service_role;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users read own order items" ON public.order_items FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public.orders o WHERE o.id = order_id AND o.user_id = auth.uid()));
CREATE POLICY "Users create own order items" ON public.order_items FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM public.orders o WHERE o.id = order_id AND o.user_id = auth.uid()));

CREATE TRIGGER categories_set_updated_at BEFORE UPDATE ON public.categories FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER products_set_updated_at BEFORE UPDATE ON public.products FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER product_variants_set_updated_at BEFORE UPDATE ON public.product_variants FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER cart_items_set_updated_at BEFORE UPDATE ON public.cart_items FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER orders_set_updated_at BEFORE UPDATE ON public.orders FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

INSERT INTO public.categories (id, name, slug) VALUES
 (1,'Audio','audio'),(2,'Footwear','footwear'),(3,'Bags','bags'),(4,'Watches','watches'),
 (5,'Home','home'),(6,'Fitness','fitness'),(7,'Deals','deals');
SELECT setval(pg_get_serial_sequence('public.categories','id'), 7);

INSERT INTO public.products (id,name,slug,description,base_price,compare_at_price,image_key,rating,reviews_count,badge,category_id) VALUES
 (1,'Aurora Wireless Headphones','aurora-wireless-headphones','Active noise cancelling over-ear headphones with 40h battery life.',179,229,'headphones',4.8,1284,'Best Seller',1),
 (2,'Trailrun Everyday Sneakers','trailrun-everyday-sneakers','Lightweight cushioned sneakers built for city miles and weekend trails.',119,149,'footwear',4.7,932,'New',2),
 (3,'Voyager Daypack 22L','voyager-daypack-22l','Water-resistant daypack with padded laptop sleeve and quick-access pocket.',89,NULL,'bags',4.6,514,NULL,3),
 (4,'Meridian Field Watch','meridian-field-watch','Sapphire crystal field watch with 100m water resistance.',249,299,'watches',4.9,376,'Best Seller',4),
 (5,'Studio Monitor Earbuds','studio-monitor-earbuds','Compact earbuds tuned for balanced studio-grade sound.',99,129,'headphones',4.5,745,'Sale',1),
 (6,'Cloudstep Running Shoes','cloudstep-running-shoes','Responsive foam running shoes with breathable knit upper.',139,NULL,'footwear',4.6,421,'New',2),
 (7,'Metro Commuter Tote','metro-commuter-tote','Structured tote with laptop compartment and magnetic closure.',75,95,'bags',4.4,288,NULL,3),
 (8,'Chrono Sport Watch','chrono-sport-watch','Solar-charged sport watch with GPS and heart-rate tracking.',329,389,'watches',4.7,199,'Sale',4);
SELECT setval(pg_get_serial_sequence('public.products','id'), 8);

INSERT INTO public.product_variants (product_id, sku, color, size, price, stock)
SELECT p.id,
       p.slug || '-' || lower(c.color) || '-' || lower(s.size),
       c.color, s.size, p.base_price,
       CASE WHEN s.size = 'XL' AND p.id % 3 = 0 THEN 0 WHEN s.size = 'S' THEN 4 ELSE 25 END
FROM public.products p
CROSS JOIN (VALUES ('Black'),('Navy'),('Sand')) AS c(color)
CROSS JOIN (VALUES ('S'),('M'),('L'),('XL')) AS s(size);
